import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
// import { Provider } from "react-redux";
// import { store } from "../redux/store";
import ProviderRedux from "@/redux/ProviderRedux";

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen w-screen overflow-hidden flex flex-row ">
        <NavBar />
        <ProviderRedux> {children}</ProviderRedux>
      </body>
    </html>
  );
}
